# Site settings
title: Abe Ratnofsky
email: aratno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm from New York, studying in Toronto, and feeling my way through CS to figure out where I fit in. I'm most captivated by technology as a cultural medium. Maybe I should have gone to art school.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aber.io" # the base hostname & protocol for your site
twitter_username: aberatnofsky
github_username:  aratno

# Build settings
markdown: kramdown
